import * as XLSX from 'xlsx'
import type { CarrierName, GatewayCode } from '@/types'

export interface ParsedRateRow {
  carrier: CarrierName
  zone: number
  weight_oz_min: number
  weight_oz_max: number
  price_usd: number
}

export interface ParsedZipZoneRow {
  carrier: CarrierName
  gateway: GatewayCode
  zip_prefix: string
  zone: number
  zone_raw: string
}

export interface ParsedLastMileResult {
  rates: { carrier: CarrierName; count: number; rows: ParsedRateRow[] }[]
  zipZones: { carrier: CarrierName; count: number; rows: ParsedZipZoneRow[] }[]
  sheets: string[]
}

// Map sheet names to carrier
const RATE_SHEET_MAP: Record<string, CarrierName> = {
  'gofo价格': 'GOFO',
  'usps价格': 'USPS',
  'uni价格': 'UNI',
}

const ZIP_SHEET_MAP: Record<string, CarrierName> = {
  // Names generated by template (carrier.toLowerCase() + '分区')
  'gofo分区': 'GOFO',
  'usps分区': 'USPS',
  'uni分区': 'UNI',
  'osm分区': 'OSM',
  // Legacy / alternative naming variants
  'gofo邮编分区': 'GOFO',
  'usps分區': 'USPS',  // traditional Chinese 區
}

const VALID_GATEWAYS: GatewayCode[] = ['LAX', 'JFK', 'ORD', 'DFW', 'MIA']

/**
 * Parse rate table sheet (Zone × Weight matrix).
 *
 * A sheet may contain TWO stacked tables — an OZ table for sub-pound weights
 * and an LB table for 1-70 lb (USPS Ground Advantage format). We auto-detect
 * the unit by scanning for a header cell containing "LB"; rows after that
 * header are multiplied by 16 to normalize to ounces.
 *
 * We also compute weight_oz_min per (carrier, zone) bracket so the bracket
 * semantics (prev_max, curr_max] are explicit in the data, not implied by
 * insertion order.
 */
const LB_TO_OZ = 16

/**
 * Locate the weight column within a sheet by scanning header rows for a cell
 * matching "Weight" / "重量" / "重量/区域". The GOFO/UNI template puts weight
 * in column 5; the USPS template uses column 0. Zone 1-8 columns follow.
 */
function detectLayout(rows: unknown[][]): { weightCol: number; zoneStartCol: number } {
  for (let r = 0; r < Math.min(rows.length, 10); r++) {
    const row = rows[r] as unknown[] | undefined
    if (!row) continue
    for (let c = 0; c < row.length; c++) {
      const cell = String(row[c] ?? '').trim().toLowerCase()
      if (/weight|重量/.test(cell)) {
        return { weightCol: c, zoneStartCol: c + 1 }
      }
    }
  }
  return { weightCol: 0, zoneStartCol: 1 }
}

function parseRateSheet(sheet: XLSX.WorkSheet, carrier: CarrierName): ParsedRateRow[] {
  const rows = XLSX.utils.sheet_to_json(sheet, { header: 1 }) as unknown[][]
  const { weightCol, zoneStartCol } = detectLayout(rows)
  const raw: Array<Omit<ParsedRateRow, 'weight_oz_min'>> = []

  // Unit defaults to OZ; switches to LB after a header row like "Weight(LBS)"
  // or when the weight sequence restarts from a small value (second table).
  let unitMultiplier = 1

  for (let r = 1; r < rows.length; r++) {
    const row = rows[r] as (string | number | undefined)[]
    if (!row || row.length <= weightCol) continue

    const rawCell = row[weightCol]
    const cellStr = String(rawCell ?? '').trim()

    // Detect unit switch: header rows like "Weight(LBS)" or "重量(LBS)"
    if (/lbs?/i.test(cellStr)) {
      unitMultiplier = LB_TO_OZ
      continue
    }
    // Second-table restart: a "Weight(OZ)" or "重量/区域" header row alone
    // doesn't flip to LB, but we track whether we've seen a numeric weight
    // since the last header — handled by the weight-reset heuristic below.

    if (!cellStr || !/\d/.test(cellStr)) continue

    const weightNum = parseFloat(cellStr)
    if (isNaN(weightNum) || weightNum <= 0) continue

    // Weight-reset heuristic: if the sequence restarts from a smaller value
    // than the previous row, the second table must be in LB.
    if (unitMultiplier === 1 && raw.length > 0) {
      const lastWeightOz = raw[raw.length - 1].weight_oz_max
      if (weightNum < lastWeightOz) unitMultiplier = LB_TO_OZ
    }

    const weightOz = weightNum * unitMultiplier

    for (let zone = 1; zone <= 8; zone++) {
      const price = parseFloat(String(row[zoneStartCol + zone - 1] ?? ''))
      if (isNaN(price) || price <= 0) continue

      raw.push({
        carrier,
        zone,
        weight_oz_max: weightOz,
        price_usd: price,
      })
    }
  }

  // Compute weight_oz_min per (carrier, zone) by sorting ASC and using the
  // previous bracket's max (0 for the first bracket).
  const byZone = new Map<number, Array<Omit<ParsedRateRow, 'weight_oz_min'>>>()
  for (const row of raw) {
    const list = byZone.get(row.zone) ?? []
    list.push(row)
    byZone.set(row.zone, list)
  }

  const results: ParsedRateRow[] = []
  for (const list of byZone.values()) {
    list.sort((a, b) => a.weight_oz_max - b.weight_oz_max)
    let prevMax = 0
    for (const row of list) {
      results.push({ ...row, weight_oz_min: prevMax })
      prevMax = row.weight_oz_max
    }
  }

  return results
}

/**
 * Parse zip-zone mapping sheet.
 * GOFO/UNI format: Zip Code | Gateway columns | Zone per gateway
 * USPS format: side-by-side tables for each origin port
 */
function parseZipZoneSheet(sheet: XLSX.WorkSheet, carrier: CarrierName): ParsedZipZoneRow[] {
  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet)
  const results: ParsedZipZoneRow[] = []

  for (const row of rows) {
    const zip = String(row['Zip Code'] ?? row['zip_code'] ?? row['ZIP Code'] ?? '').trim()
    if (!zip) continue

    // Check each gateway column
    for (const gw of VALID_GATEWAYS) {
      const zoneRaw = String(row[gw] ?? row[gw.toLowerCase()] ?? '').trim()
      if (!zoneRaw || zoneRaw === '-') continue

      const zoneNum = parseInt(zoneRaw.replace(/[*+]/g, ''))
      if (isNaN(zoneNum) || zoneNum < 1 || zoneNum > 9) continue

      results.push({
        carrier,
        gateway: gw,
        zip_prefix: zip,
        zone: zoneNum,
        zone_raw: zoneRaw,
      })
    }
  }

  return results
}

export function parseLastMileExcel(buffer: ArrayBuffer): ParsedLastMileResult {
  const wb = XLSX.read(buffer, { type: 'array' })

  const rates: ParsedLastMileResult['rates'] = []
  const zipZones: ParsedLastMileResult['zipZones'] = []

  for (const sheetName of wb.SheetNames) {
    const sheet = wb.Sheets[sheetName]
    const normalizedName = sheetName.toLowerCase().trim()

    // Check rate sheets
    for (const [key, carrier] of Object.entries(RATE_SHEET_MAP)) {
      if (normalizedName === key.toLowerCase() || sheetName === key) {
        const parsed = parseRateSheet(sheet, carrier)
        if (parsed.length > 0) {
          rates.push({ carrier, count: parsed.length, rows: parsed })
        }
      }
    }

    // Check zip-zone sheets
    for (const [key, carrier] of Object.entries(ZIP_SHEET_MAP)) {
      if (normalizedName === key.toLowerCase() || sheetName === key) {
        const parsed = parseZipZoneSheet(sheet, carrier)
        if (parsed.length > 0) {
          zipZones.push({ carrier, count: parsed.length, rows: parsed })
        }
      }
    }
  }

  return { rates, zipZones, sheets: wb.SheetNames }
}
